server.port=8080
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/achiever_logistics_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=achiever-logistics-backend