# Server
server.port=8080

# Database - Achiever Logistics
spring.datasource.url=jdbc:mysql://localhost:3306/achiever_logistics_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App Name
spring.application.name=achiever-logistics-backend